import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Generate Schema Registry
const schemaDir = path.join(__dirname, '../schema');
const files = fs.readdirSync(schemaDir).filter(f => f.endsWith('.schema.ts') && f !== 'registry.ts');

let imports = '';
let registryEntries = '';

for (const file of files) {
  const name = file.replace('.schema.ts', '');
  imports += `import ${name} from './${file.replace('.ts', '')}';\n`;
  registryEntries += `  ${name}Schema: ${name},\n`;
}

const registryContent = `// Auto-generated by scripts/generate-migration.ts
${imports}
export const registry = {
${registryEntries}};

export type Registry = typeof registry;
export type ContentType = keyof Registry;
`;

fs.writeFileSync(path.join(schemaDir, 'registry.ts'), registryContent);
console.log('✅ Generated schema/registry.ts');

// 2. Load Registry for Diffing
// We can use a dynamic import of the generated registry or load schema definitions manually
// To be safe and avoid compilation issues with registry imports, we will read the schema definitions by importing files directly.
const registry: Record<string, any> = {};
for (const file of files) {
  const name = file.replace('.schema.ts', '');
  const schemaPath = path.join(schemaDir, file);
  // Read schema definition dynamically
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const schemaModule = require(schemaPath);
  const schema = schemaModule.default || schemaModule[name + 'Schema'] || schemaModule.postSchema;
  if (schema && schema.slug) {
    registry[schema.slug] = schema;
  }
}

// 3. Diff with D1 Local Database
let existingTables: Record<string, string[]> = {}; // tableName -> columnNames

try {
  const stdout = execSync(
    'npx wrangler d1 execute cms-db --local --json --command "SELECT name FROM sqlite_master WHERE type=\'table\' AND name NOT LIKE \'_cf_%\' AND name NOT LIKE \'sqlite_%\'"',
    { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] }
  );
  
  const jsonStart = stdout.indexOf('[');
  if (jsonStart !== -1) {
    const data = JSON.parse(stdout.substring(jsonStart));
    const tables = data[0]?.results || [];
    for (const t of tables) {
      const tableName = t.name;
      const colStdout = execSync(
        `npx wrangler d1 execute cms-db --local --json --command "PRAGMA table_info(${tableName})"`,
        { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] }
      );
      const colStart = colStdout.indexOf('[');
      if (colStart !== -1) {
        const colData = JSON.parse(colStdout.substring(colStart));
        const columns = (colData[0]?.results || []).map((c: any) => c.name);
        existingTables[tableName] = columns;
      }
    }
  }
} catch (err) {
  console.log('⚠️ Could not connect to local D1 database. Generating migrations assuming empty database.');
}

// 4. Generate SQL Migrations
function getSqlType(fieldType: string) {
  if (fieldType === 'boolean') return 'INTEGER';
  return 'TEXT';
}

const sqlStatements: string[] = [];

for (const tableName of Object.keys(registry)) {
  const schema = registry[tableName];
  const fields = schema.fields;

  if (!existingTables[tableName]) {
    let columnsSql = [
      'id TEXT PRIMARY KEY',
      'owner TEXT DEFAULT \'salmeen\'',
      'created_at TEXT DEFAULT CURRENT_TIMESTAMP',
      'updated_at TEXT DEFAULT CURRENT_TIMESTAMP',
      'is_deleted INTEGER DEFAULT 0',
      'published_version INTEGER DEFAULT 1',
      'draft_version INTEGER DEFAULT 1'
    ];
    for (const field of fields) {
      const type = getSqlType(field.type);
      columnsSql.push(`${field.name} ${type}`);
    }
    sqlStatements.push(`CREATE TABLE ${tableName} (\n  ${columnsSql.join(',\n  ')}\n);`);
  } else {
    const existingCols = existingTables[tableName];
    if (!existingCols.includes('owner')) {
      sqlStatements.push(`ALTER TABLE ${tableName} ADD COLUMN owner TEXT DEFAULT 'salmeen';`);
    }
    for (const field of fields) {
      if (!existingCols.includes(field.name)) {
        const type = getSqlType(field.type);
        sqlStatements.push(`ALTER TABLE ${tableName} ADD COLUMN ${field.name} ${type};`);
      }
    }
  }
}

const migrationsDir = path.join(__dirname, '../migrations');
if (!fs.existsSync(migrationsDir)) {
  fs.mkdirSync(migrationsDir, { recursive: true });
}

if (sqlStatements.length === 0) {
  console.log('✅ Database schema is up to date. No migration generated.');
} else {
  const migrationFiles = fs.readdirSync(migrationsDir).filter(f => f.endsWith('.sql'));
  let nextNum = 1;
  if (migrationFiles.length > 0) {
    const nums = migrationFiles.map(f => parseInt(f.split('_')[0], 10)).filter(n => !isNaN(n));
    nextNum = Math.max(...nums) + 1;
  }
  const nextMigrationName = `${String(nextNum).padStart(4, '0')}_auto_migration.sql`;
  const nextMigrationPath = path.join(migrationsDir, nextMigrationName);

  const sqlContent = sqlStatements.join('\n\n');
  fs.writeFileSync(nextMigrationPath, sqlContent);
  console.log(`✅ Generated migration: ${nextMigrationName}`);
  console.log(sqlContent);
}
