// Auto-generated by scripts/generate-migration.ts
import certificate from './certificate.schema';
import hero from './hero.schema';
import logo from './logo.schema';
import media from './media.schema';
import project from './project.schema';

export const registry = {
  certificateSchema: certificate,
  heroSchema: hero,
  logoSchema: logo,
  mediaSchema: media,
  projectSchema: project,
};

export type Registry = typeof registry;
export type ContentType = keyof Registry;
